# Generated by Django 4.0.4 on 2022-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='START',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(choices=[('서울동부혈액원', '서울동부혈액원'), ('서울남부혈액원', '서울남부혈액원'), ('서울중앙혈액원', '서울중앙혈액원'), ('서울특별시보라매병원', '보라매병원'), ('재단법인아산사회복지재단서울아산병원', '서울아산병원'), ('학교법인연세대학교의과대학세브란스병원', '연세대학교세브란스병원')], max_length=20)),
            ],
        ),
    ]
