# Generated by Django 4.0.4 on 2022-06-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='START',
        ),
    ]
